version: '3.8'

x-besu: &besu
  image: hyperledger/besu:latest

services:
  besu-node1:
    << : *besu
    hostname: besu-validator-1
    volumes:
      - "./data/node1:/var/lib/besu" # mount to host
      - "./config/genesis.json:/config/genesis.json"
      - "./keystore/key_node1:/config/key" # mount to host
    command:
      - --data-path=/var/lib/besu
      - --genesis-file=/config/genesis.json
      - --rpc-http-enabled
      - --rpc-http-host=0.0.0.0
      - --rpc-http-port=8545
      - --rpc-ws-enabled
      - --rpc-http-api=ETH,NET,CLIQUE,TXPOOL,WEB3
      - --rpc-ws-api=ETH,NET,CLIQUE,TXPOOL,WEB3
      - --rpc-http-cors-origins=*
      - --miner-enabled
      - --miner-coinbase=0x32d5a21376c0df3f98200a00380b06adee341b91
      - --node-private-key-file=/config/key
      - --nat-method=AUTO
      - --host-allowlist=*
      - --engine-host-allowlist=*
      - --tx-pool-max-future-by-sender=1000000
      - --tx-pool-max-prioritized=1000000
      - --tx-pool-layer-max-capacity=125000000
      - --rpc-http-max-active-connections=100000
      - --Xplugin-rocksdb-max-open-files=4096 # perf
      - --Xplugin-rocksdb-cache-capacity=314572800 # perf
      - --Xplugin-rocksdb-background-thread-count=64 # perf
      - --rpc-http-max-batch-size=-1
      - --rpc-http-max-request-content-length=314572800 
      - --Xpoa-block-txs-selection-max-time=90
      - --bootnodes=enode://8b140bbda279a4459a6bde6d03318aff6efff6de197b6939e2cdbbd986344024a66daa6d4a7e69bd202873b1edf37bb06c600f665a7eabc2caf44c43756f0e20@172.18.1.2:30303
    networks:
      loaffinity-evm-besu-qbft:
        ipv4_address: 172.18.1.2
  besu-node2:
    << : *besu
    hostname: besu-validator-2
    volumes:
      - "./data/node2:/var/lib/besu" # mount to host
      - "./config/genesis.json:/config/genesis.json"
      - "./keystore/key_node2:/config/key" # mount to host
    command:
      - --data-path=/var/lib/besu
      - --genesis-file=/config/genesis.json
      - --rpc-http-enabled
      - --rpc-http-host=0.0.0.0
      - --rpc-http-port=8545
      - --rpc-ws-enabled
      - --rpc-http-api=ETH,NET,CLIQUE,TXPOOL,WEB3
      - --rpc-ws-api=ETH,NET,CLIQUE,TXPOOL,WEB3
      - --rpc-http-cors-origins=*
      - --miner-enabled
      - --miner-coinbase=0x6f7090364d4aE2C1819693D6382b74C7D004b4B8
      - --node-private-key-file=/config/key
      - --nat-method=AUTO
      - --host-allowlist=*
      - --engine-host-allowlist=*
      - --tx-pool-max-future-by-sender=1000000
      - --tx-pool-max-prioritized=1000000
      - --tx-pool-layer-max-capacity=125000000
      - --rpc-http-max-active-connections=100000
      - --Xplugin-rocksdb-max-open-files=4096 # perf
      - --Xplugin-rocksdb-cache-capacity=314572800 # perf
      - --Xplugin-rocksdb-background-thread-count=64 # perf
      - --rpc-http-max-request-content-length=314572800 
      - --rpc-http-max-batch-size=-1
      - --Xpoa-block-txs-selection-max-time=90
      - --bootnodes=enode://8b140bbda279a4459a6bde6d03318aff6efff6de197b6939e2cdbbd986344024a66daa6d4a7e69bd202873b1edf37bb06c600f665a7eabc2caf44c43756f0e20@172.18.1.2:30303
    networks:
      loaffinity-evm-besu-qbft:
        ipv4_address: 172.18.1.3
  besu-node3:
    << : *besu
    hostname: besu-validator-3
    volumes:
      - "./data/node3:/var/lib/besu" # mount to host
      - "./config/genesis.json:/config/genesis.json"
      - "./keystore/key_node3:/config/key" # mount to host
    command:
      - --data-path=/var/lib/besu
      - --genesis-file=/config/genesis.json
      - --rpc-http-enabled
      - --rpc-http-host=0.0.0.0
      - --rpc-http-port=8545
      - --rpc-ws-enabled
      - --rpc-http-api=ETH,NET,CLIQUE,TXPOOL,WEB3
      - --rpc-ws-api=ETH,NET,CLIQUE,TXPOOL,WEB3
      - --rpc-http-cors-origins=*
      - --miner-enabled
      - --miner-coinbase=0x7c55259cc19af2ab5f417680884b5b642e20cdc4
      - --node-private-key-file=/config/key
      - --nat-method=AUTO
      - --host-allowlist=*
      - --engine-host-allowlist=*
      - --tx-pool-max-future-by-sender=1000000
      - --tx-pool-max-prioritized=1000000
      - --tx-pool-layer-max-capacity=125000000
      - --rpc-http-max-active-connections=100000
      - --Xplugin-rocksdb-max-open-files=4096 # perf
      - --Xplugin-rocksdb-cache-capacity=314572800 # perf
      - --Xplugin-rocksdb-background-thread-count=64 # perf
      - --rpc-http-max-request-content-length=314572800 
      - --rpc-http-max-batch-size=-1
      - --Xpoa-block-txs-selection-max-time=90
      - --bootnodes=enode://8b140bbda279a4459a6bde6d03318aff6efff6de197b6939e2cdbbd986344024a66daa6d4a7e69bd202873b1edf37bb06c600f665a7eabc2caf44c43756f0e20@172.18.1.2:30303
    ports:
      - "30303:30303"
      - "8545:8545"
      - "8546:8546"
    networks:
      loaffinity-evm-besu-qbft:
        ipv4_address: 172.18.1.4
networks:  
    loaffinity-evm-besu-qbft:
        name: loaffinity-evm-besu-qbft
        driver: bridge
        ipam:
            driver: default
            config:
            - subnet: 172.18.1.0/16